# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
